#!/usr/bin/env python3
"""
Panoptica365 — Quick Assessment Report Generator (v0.1.6)

Renders the Opus deep gap analysis into a narrative advisory PDF: a branded
cover page, headline metrics + charts, then Conditional Access / Intune /
Security Settings sections (each with narrative + strengths + gaps), a
strengths summary, and a prioritized action list.

Input JSON (argv[1]) is assembled by src/routes/api-reports.js — see the
quick-assessment route. Output PDF path is argv[2].

Usage: python3 generate-quick-assessment-report.py <input.json> <output.pdf>
"""

import sys
import os
import json
import html
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white
from reportlab.lib.utils import ImageReader
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether,
    PageBreak, Image as RLImage,
)

import matplotlib
matplotlib.use('Agg')  # headless — no display
import matplotlib.pyplot as plt

# Shared email-auth rendering logic — one implementation across both report
# generators (Security Posture + Quick Assessment) so they can't drift. Ensure
# the script's own dir is importable whether run as a script or via importlib.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _report_email_auth import (  # noqa: E402
    generate_email_auth_gauge, email_auth_label, mechanism_rows,
)

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ─── Palette (consistent with the other Panoptica reports) ───
COLORS = {
    'primary':    '#2C3E50',
    'accent':     '#C9A961',
    'text':       '#333333',
    'text_light': '#666666',
    'rule':       '#D9D9D9',
    'band':       '#F4F2EC',
    'high':       '#C0392B',
    'medium':     '#D68910',
    'low':        '#7F8C8D',
    'good':       '#1E8449',
}

# ─── Localized static chrome (the AI narrative is already localized) ───
STRINGS = {
    'en': {
        'title': 'Quick Assessment',
        'subtitle': 'Microsoft 365 Security — Point-in-Time Assessment',
        'cover_prepared_by': 'Prepared by {msp}',
        'tenant': 'Tenant',
        'generated': 'Generated',
        'captured': 'Configuration captured',
        'hl_secure': 'Secure Score',
        'hl_mfa': 'MFA Registration',
        'hl_ca': 'CA Policies',
        'hl_settings': 'Security Settings',
        'sec_overall': 'Overall Posture',
        'sec_ca': 'Conditional Access',
        'sec_intune': 'Intune & Device Management',
        'sec_settings': 'Security Settings Posture',
        'sec_strengths': 'Strengths',
        'sec_actions': 'Priority Actions',
        'exec_summary_title': 'Executive Summary',
        'exec_risks_label': "What's at stake",
        'exec_path_label': 'Recommended next step',
        'exec_outlook_label': 'Where this leads',
        'sub_working': 'What is working',
        'sub_gaps': 'Gaps & recommendations',
        'deployable': 'One-click template available',
        'tpl': 'Template',
        'none': 'No items noted.',
        'prio_high': 'High',
        'prio_medium': 'Medium',
        'prio_low': 'Low',
        'chart_score': 'Microsoft Secure Score',
        'chart_findings': 'Findings by Priority',
        'findings_unit': 'findings',
        'attribution': 'Generated by Panoptica365',
        'page': 'Page',
        # ─── Enrichment tables (identity hygiene / application risk) ───
        'er_sec_identity': 'Identity Hygiene',
        'er_sec_admins': 'Accounts with Admin Roles',
        'er_sec_inactive': 'Inactive Accounts',
        'er_sec_breakglass': 'Break-Glass (Emergency Access)',
        'er_sec_app_risk': 'Application Risk',
        'er_sec_app_gov': 'Application Governance',
        'er_sec_known_good': 'Known-Good Applications',
        'er_sec_other_apps': 'Other Applications',
        'er_col_account': 'Account',
        'er_col_roles': 'Roles',
        'er_col_enabled': 'Enabled',
        'er_col_mfa': 'MFA',
        'er_col_activity': 'Last Activity',
        'er_col_type': 'Type',
        'er_col_app': 'Application',
        'er_col_publisher': 'Publisher',
        'er_col_verdict': 'Risk Verdict',
        'er_col_permissions': 'Permissions',
        'er_col_drift': 'Drift',
        'er_yes': 'Yes',
        'er_no': 'No',
        'er_unknown': 'Unknown',
        'er_member': 'Member',
        'er_guest': 'Guest',
        'er_verdict_green': 'Green',
        'er_verdict_yellow': 'Yellow',
        'er_verdict_red': 'Red',
        'er_verdict_none': 'Not evaluated',
        'er_drift_yes': 'Drifted',
        'er_never_redeemed': 'Never redeemed',
        'er_breakglass_tag': 'break-glass',
        'er_bg_group_label': 'Group',
        'er_bg_members_label': 'Members',
        'er_none': 'None',
        'er_more': '(+{n} more)',
        'er_no_admins': 'No accounts hold admin roles.',
        'er_no_inactive': 'No inactive accounts.',
        'er_all_known_good': 'All applications are tagged Known-Good.',
        'er_identity_unavailable': 'Access Review data has not been captured for this tenant. Run an Access Review to populate identity hygiene.',
        'er_apps_unavailable': 'Application inventory is not available. Run the Applications scan.',
        'er_bg_not_configured': 'No break-glass (emergency-access) group is configured for this tenant.',
        'er_bg_members_unavailable': 'Group membership could not be read at report time.',
        'er_threshold_note': 'Inactivity threshold: {n} days.',
        # ─── Report polish v0.2.24 (shared with the Security Posture report) ───
        'er_sec_inactive_members': 'Inactive Members',
        'er_sec_inactive_guests': 'Inactive External / Guest Accounts',
        'er_guest_external': 'Guest/External',
        'er_no_inactive_members': 'No inactive member accounts.',
        'er_no_inactive_guests': 'No inactive guest accounts.',
        'er_guest_count_note': '{inactive} of {total} guest account(s) inactive.',
        'email_auth_title': 'Email Authentication',
        'email_auth_intro': "DNS email-authentication posture for this tenant's primary sending domain.",
        'email_auth_unavailable': 'Email authentication has not been audited for this tenant. Run a Refresh on the Email Auth tab to populate it.',
        'ea_col_mechanism': 'Mechanism',
        'ea_col_status': 'Status',
        'ea_col_detail': 'Detail',
        'email_auth_other_domains': 'Other mail domains',
        'email_auth_nonmail_note': 'Non-mail domains should publish v=spf1 -all and DMARC p=reject to prevent spoofing: {domains}',
    },
    'fr': {
        'title': 'Évaluation rapide',
        'subtitle': 'Sécurité Microsoft 365 — Évaluation ponctuelle',
        'cover_prepared_by': 'Préparé par {msp}',
        'tenant': 'Locataire',
        'generated': 'Généré le',
        'captured': 'Configuration relevée le',
        'hl_secure': 'Score de sécurité',
        'hl_mfa': 'Inscription MFA',
        'hl_ca': 'Politiques AC',
        'hl_settings': 'Paramètres de sécurité',
        'sec_overall': 'Posture globale',
        'sec_ca': 'Accès conditionnel',
        'sec_intune': 'Intune et gestion des appareils',
        'sec_settings': 'Posture des paramètres de sécurité',
        'sec_strengths': 'Points forts',
        'sec_actions': 'Actions prioritaires',
        'exec_summary_title': 'Sommaire exécutif',
        'exec_risks_label': 'Ce qui est en jeu',
        'exec_path_label': 'Prochaine étape recommandée',
        'exec_outlook_label': 'Où cela vous mène',
        'sub_working': 'Ce qui fonctionne',
        'sub_gaps': 'Lacunes et recommandations',
        'deployable': 'Modèle déployable en un clic',
        'tpl': 'Modèle',
        'none': 'Aucun élément relevé.',
        'prio_high': 'Élevée',
        'prio_medium': 'Moyenne',
        'prio_low': 'Faible',
        'chart_score': 'Score de sécurité Microsoft',
        'chart_findings': 'Constats par priorité',
        'findings_unit': 'constats',
        'attribution': 'Généré par Panoptica365',
        'page': 'Page',
        # ─── Tableaux d'enrichissement (hygiène des identités / risque applicatif) ───
        'er_sec_identity': 'Hygiène des identités',
        'er_sec_admins': "Comptes avec rôles d'administration",
        'er_sec_inactive': 'Comptes inactifs',
        'er_sec_breakglass': "Compte d'urgence (bris de glace)",
        'er_sec_app_risk': 'Risque applicatif',
        'er_sec_app_gov': 'Gouvernance des applications',
        'er_sec_known_good': 'Applications approuvées',
        'er_sec_other_apps': 'Autres applications',
        'er_col_account': 'Compte',
        'er_col_roles': 'Rôles',
        'er_col_enabled': 'Activé',
        'er_col_mfa': 'MFA',
        'er_col_activity': 'Dernière activité',
        'er_col_type': 'Type',
        'er_col_app': 'Application',
        'er_col_publisher': 'Éditeur',
        'er_col_verdict': 'Verdict de risque',
        'er_col_permissions': 'Autorisations',
        'er_col_drift': 'Dérive',
        'er_yes': 'Oui',
        'er_no': 'Non',
        'er_unknown': 'Inconnu',
        'er_member': 'Membre',
        'er_guest': 'Invité',
        'er_verdict_green': 'Vert',
        'er_verdict_yellow': 'Jaune',
        'er_verdict_red': 'Rouge',
        'er_verdict_none': 'Non évalué',
        'er_drift_yes': 'En dérive',
        'er_never_redeemed': 'Jamais accepté',
        'er_breakglass_tag': "compte d'urgence",
        'er_bg_group_label': 'Groupe',
        'er_bg_members_label': 'Membres',
        'er_none': 'Aucun',
        'er_more': '(+{n} de plus)',
        'er_no_admins': "Aucun compte ne détient de rôle d'administration.",
        'er_no_inactive': 'Aucun compte inactif.',
        'er_all_known_good': 'Toutes les applications sont approuvées.',
        'er_identity_unavailable': "Les données de revue des accès n'ont pas été recueillies pour ce locataire. Lancez une revue des accès pour renseigner l'hygiène des identités.",
        'er_apps_unavailable': "L'inventaire des applications n'est pas disponible. Lancez l'analyse des applications.",
        'er_bg_not_configured': "Aucun groupe de compte d'urgence (bris de glace) n'est configuré pour ce locataire.",
        'er_bg_members_unavailable': "L'appartenance au groupe n'a pas pu être lue au moment du rapport.",
        'er_threshold_note': "Seuil d'inactivité : {n} jours.",
        # ─── Report polish v0.2.24 (partagé avec le rapport de posture) ───
        'er_sec_inactive_members': 'Membres inactifs',
        'er_sec_inactive_guests': 'Comptes externes / invités inactifs',
        'er_guest_external': 'Invité/Externe',
        'er_no_inactive_members': 'Aucun compte membre inactif.',
        'er_no_inactive_guests': 'Aucun compte invité inactif.',
        'er_guest_count_note': '{inactive} compte(s) invité sur {total} inactif(s).',
        'email_auth_title': 'Authentification du courriel',
        'email_auth_intro': "Posture d'authentification des courriels (DNS) pour le domaine d'envoi principal de ce locataire.",
        'email_auth_unavailable': "L'authentification des courriels n'a pas été vérifiée pour ce locataire. Lancez une actualisation dans l'onglet Authentification du courriel pour la renseigner.",
        'ea_col_mechanism': 'Mécanisme',
        'ea_col_status': 'Statut',
        'ea_col_detail': 'Détail',
        'email_auth_other_domains': 'Autres domaines de courriel',
        'email_auth_nonmail_note': "Les domaines sans courriel devraient publier v=spf1 -all et DMARC p=reject pour empêcher l'usurpation : {domains}",
    },
    'es': {
        'title': 'Evaluación rápida',
        'subtitle': 'Seguridad de Microsoft 365 — Evaluación puntual',
        'cover_prepared_by': 'Preparado por {msp}',
        'tenant': 'Inquilino',
        'generated': 'Generado el',
        'captured': 'Configuración capturada el',
        'hl_secure': 'Puntuación de seguridad',
        'hl_mfa': 'Registro de MFA',
        'hl_ca': 'Políticas de AC',
        'hl_settings': 'Configuración de seguridad',
        'sec_overall': 'Postura general',
        'sec_ca': 'Acceso condicional',
        'sec_intune': 'Intune y gestión de dispositivos',
        'sec_settings': 'Postura de configuración de seguridad',
        'sec_strengths': 'Fortalezas',
        'sec_actions': 'Acciones prioritarias',
        'exec_summary_title': 'Resumen ejecutivo',
        'exec_risks_label': 'Lo que está en juego',
        'exec_path_label': 'Próximo paso recomendado',
        'exec_outlook_label': 'Adónde lleva esto',
        'sub_working': 'Lo que funciona',
        'sub_gaps': 'Brechas y recomendaciones',
        'deployable': 'Plantilla disponible en un clic',
        'tpl': 'Plantilla',
        'none': 'Sin elementos.',
        'prio_high': 'Alta',
        'prio_medium': 'Media',
        'prio_low': 'Baja',
        'chart_score': 'Puntuación de seguridad de Microsoft',
        'chart_findings': 'Hallazgos por prioridad',
        'findings_unit': 'hallazgos',
        'attribution': 'Generado por Panoptica365',
        'page': 'Página',
        # ─── Tablas de enriquecimiento (higiene de identidades / riesgo de aplicaciones) ───
        'er_sec_identity': 'Higiene de identidades',
        'er_sec_admins': 'Cuentas con roles de administrador',
        'er_sec_inactive': 'Cuentas inactivas',
        'er_sec_breakglass': 'Acceso de emergencia (break-glass)',
        'er_sec_app_risk': 'Riesgo de aplicaciones',
        'er_sec_app_gov': 'Gobernanza de aplicaciones',
        'er_sec_known_good': 'Aplicaciones aprobadas',
        'er_sec_other_apps': 'Otras aplicaciones',
        'er_col_account': 'Cuenta',
        'er_col_roles': 'Roles',
        'er_col_enabled': 'Habilitado',
        'er_col_mfa': 'MFA',
        'er_col_activity': 'Última actividad',
        'er_col_type': 'Tipo',
        'er_col_app': 'Aplicación',
        'er_col_publisher': 'Editor',
        'er_col_verdict': 'Veredicto de riesgo',
        'er_col_permissions': 'Permisos',
        'er_col_drift': 'Desviación',
        'er_yes': 'Sí',
        'er_no': 'No',
        'er_unknown': 'Desconocido',
        'er_member': 'Miembro',
        'er_guest': 'Invitado',
        'er_verdict_green': 'Verde',
        'er_verdict_yellow': 'Amarillo',
        'er_verdict_red': 'Rojo',
        'er_verdict_none': 'Sin evaluar',
        'er_drift_yes': 'Desviada',
        'er_never_redeemed': 'Nunca aceptada',
        'er_breakglass_tag': 'break-glass',
        'er_bg_group_label': 'Grupo',
        'er_bg_members_label': 'Miembros',
        'er_none': 'Ninguno',
        'er_more': '(+{n} más)',
        'er_no_admins': 'Ninguna cuenta tiene roles de administrador.',
        'er_no_inactive': 'Ninguna cuenta inactiva.',
        'er_all_known_good': 'Todas las aplicaciones están aprobadas.',
        'er_identity_unavailable': 'No se han recopilado datos de revisión de acceso para este inquilino. Ejecute una revisión de acceso para completar la higiene de identidades.',
        'er_apps_unavailable': 'El inventario de aplicaciones no está disponible. Ejecute el análisis de aplicaciones.',
        'er_bg_not_configured': 'No hay configurado ningún grupo de acceso de emergencia (break-glass) para este inquilino.',
        'er_bg_members_unavailable': 'No se pudo leer la pertenencia al grupo al momento del informe.',
        'er_threshold_note': 'Umbral de inactividad: {n} días.',
        # ─── Report polish v0.2.24 (compartido con el informe de postura) ───
        'er_sec_inactive_members': 'Miembros inactivos',
        'er_sec_inactive_guests': 'Cuentas externas / invitadas inactivas',
        'er_guest_external': 'Invitado/Externo',
        'er_no_inactive_members': 'Ninguna cuenta miembro inactiva.',
        'er_no_inactive_guests': 'Ninguna cuenta invitada inactiva.',
        'er_guest_count_note': '{inactive} de {total} cuenta(s) invitada(s) inactiva(s).',
        'email_auth_title': 'Autenticación de correo',
        'email_auth_intro': 'Postura de autenticación de correo (DNS) del dominio de envío principal de este inquilino.',
        'email_auth_unavailable': 'La autenticación de correo no se ha auditado para este inquilino. Ejecute Actualizar en la pestaña Autenticación de correo para completarla.',
        'ea_col_mechanism': 'Mecanismo',
        'ea_col_status': 'Estado',
        'ea_col_detail': 'Detalle',
        'email_auth_other_domains': 'Otros dominios de correo',
        'email_auth_nonmail_note': 'Los dominios sin correo deberían publicar v=spf1 -all y DMARC p=reject para evitar la suplantación: {domains}',
    },
}


def esc(value):
    """Escape text for ReportLab paragraph markup; lift **bold** to <b>."""
    if value is None:
        return ''
    text = html.escape(str(value), quote=False)
    while '**' in text:
        text = text.replace('**', '<b>', 1)
        if '**' in text:
            text = text.replace('**', '</b>', 1)
        else:
            text += '</b>'
    return text


def fmt_pct(value):
    if value is None:
        return '—'
    try:
        return f'{round(float(value))}%'
    except (TypeError, ValueError):
        return str(value)


def fmt_dt(iso):
    if not iso:
        return '—'
    try:
        return datetime.fromisoformat(str(iso).replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M UTC')
    except ValueError:
        return str(iso)


def find_cover_image():
    """Canonical Panoptica365 cover; fall back to the repo-root asset."""
    for candidate in (
        os.path.join(PROJECT_ROOT, 'public', 'img', 'report-cover.png'),
        os.path.join(PROJECT_ROOT, 'Panoptica365 Report Cover.png'),
    ):
        if os.path.exists(candidate):
            return candidate
    return None


def build_styles():
    base = getSampleStyleSheet()
    styles = {}
    styles['Subtitle'] = ParagraphStyle(
        'QaSubtitle', parent=base['Normal'], fontName='Helvetica',
        fontSize=11, textColor=HexColor(COLORS['text_light']), leading=15)
    styles['Meta'] = ParagraphStyle(
        'QaMeta', parent=base['Normal'], fontName='Helvetica',
        fontSize=9.5, textColor=HexColor(COLORS['text_light']), leading=14)
    styles['Section'] = ParagraphStyle(
        'QaSection', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=14, textColor=white, leading=18)
    styles['SubHead'] = ParagraphStyle(
        'QaSubHead', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=10.5, textColor=HexColor(COLORS['primary']), leading=14,
        spaceBefore=8, spaceAfter=3)
    styles['Body'] = ParagraphStyle(
        'QaBody', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=15,
        spaceAfter=6, alignment=TA_LEFT)
    styles['Bullet'] = ParagraphStyle(
        'QaBullet', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=14,
        leftIndent=14, bulletIndent=4, spaceAfter=3)
    styles['Gap'] = ParagraphStyle(
        'QaGap', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=14,
        spaceAfter=2)
    styles['GapMeta'] = ParagraphStyle(
        'QaGapMeta', parent=base['Normal'], fontName='Helvetica-Oblique',
        fontSize=8.5, textColor=HexColor(COLORS['text_light']), leading=12,
        spaceAfter=8)
    styles['CardValue'] = ParagraphStyle(
        'QaCardValue', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=18, textColor=HexColor(COLORS['primary']), leading=20,
        alignment=TA_CENTER)
    styles['CardLabel'] = ParagraphStyle(
        'QaCardLabel', parent=base['Normal'], fontName='Helvetica',
        fontSize=8, textColor=HexColor(COLORS['text_light']), leading=10,
        alignment=TA_CENTER)
    styles['Caption'] = ParagraphStyle(
        'QaCaption', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=8.5, textColor=HexColor(COLORS['text_light']), leading=11,
        alignment=TA_CENTER)
    return styles


# ─── Charts (matplotlib, headless) ───

def chart_score_gauge(score_pct, buf):
    """Donut gauge for the Microsoft Secure Score. Returns False if no data."""
    if score_pct is None:
        return False
    try:
        score = float(score_pct)
    except (TypeError, ValueError):
        return False

    fig, ax = plt.subplots(figsize=(2.6, 2.6))
    ring = COLORS['good'] if score >= 70 else COLORS['medium'] if score >= 45 else COLORS['high']
    ax.pie([score, max(0.0, 100 - score)], colors=[ring, '#E8E8E8'],
           startangle=90, counterclock=False,
           wedgeprops=dict(width=0.32, edgecolor='white', linewidth=2))
    ax.text(0, 0, f'{round(score)}%', ha='center', va='center',
            fontsize=26, fontweight='bold', color=COLORS['primary'])
    ax.set(aspect='equal')
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    return True


def chart_findings_donut(counts, buf, S):
    """Donut of findings by priority (high/medium/low). False if no findings."""
    order = [('high', S['prio_high'], COLORS['high']),
             ('medium', S['prio_medium'], COLORS['medium']),
             ('low', S['prio_low'], COLORS['low'])]
    values, colors_list = [], []
    for key, _label, color in order:
        cnt = counts.get(key, 0)
        if cnt > 0:
            values.append(cnt)
            colors_list.append(color)
    total = sum(values)
    if total == 0:
        return False

    fig, ax = plt.subplots(figsize=(2.6, 2.6))
    ax.pie(values, colors=colors_list, startangle=90, counterclock=False,
           wedgeprops=dict(width=0.32, edgecolor='white', linewidth=2))
    ax.text(0, 0.07, str(total), ha='center', va='center',
            fontsize=24, fontweight='bold', color=COLORS['primary'])
    ax.text(0, -0.20, S['findings_unit'], ha='center', va='center',
            fontsize=8, color=COLORS['text_light'])
    ax.set(aspect='equal')
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    return True


def prose(text, styles):
    """Split a narrative string on blank lines into separate paragraphs."""
    flows = []
    if not text:
        return flows
    for chunk in [c.strip() for c in str(text).replace('\r', '').split('\n\n') if c.strip()]:
        flows.append(Paragraph(esc(chunk).replace('\n', '<br/>'), styles['Body']))
    return flows


def section_header(label, styles, width):
    """A full-width colored section bar."""
    tbl = Table([[Paragraph(esc(label), styles['Section'])]], colWidths=[width])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor(COLORS['primary'])),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    return tbl


def section(label, content_flows, styles, width):
    """A section: the header bar is glued to its first content flowable via
    KeepTogether, so a header can never be orphaned at the foot of a page."""
    header = section_header(label, styles, width)
    if not content_flows:
        return [header, Spacer(1, 12)]
    head_group = KeepTogether([header, Spacer(1, 8), content_flows[0]])
    return [head_group] + content_flows[1:] + [Spacer(1, 12)]


def priority_label(priority, S):
    p = (priority or '').lower()
    if p == 'high':
        return S['prio_high'], COLORS['high']
    if p == 'low':
        return S['prio_low'], COLORS['low']
    return S['prio_medium'], COLORS['medium']


def gap_flowables(gap, styles, S):
    """The raw flowables for one finding — title + priority tag, detail, and
    the optional template line. Returned as a flat list so callers can wrap
    them in a single (non-nested) KeepTogether."""
    label, color = priority_label(gap.get('priority'), S)
    head = (f'<font color="{color}"><b>[{esc(label)}]</b></font> '
            f'<b>{esc(gap.get("title") or "")}</b>')
    out = [Paragraph(head, styles['Gap'])]
    if gap.get('detail'):
        out.append(Paragraph(esc(gap.get('detail')), styles['Gap']))
    tpl = gap.get('deployable_template')
    if tpl:
        out.append(Paragraph(
            f'&#10003; {esc(S["deployable"])} — {esc(S["tpl"])}: <b>{esc(tpl)}</b>',
            styles['GapMeta']))
    else:
        out.append(Spacer(1, 4))
    return out


def render_area(area, styles, S):
    """Render a CA / Intune / Security-Settings section's content flowables.
    Each finding is one atomic KeepTogether and the "Gaps" sub-heading is
    flat-glued to the first finding — no nested KeepTogethers, which would
    mis-measure and strand whitespace at page ends."""
    flows = []
    flows.extend(prose((area or {}).get('narrative'), styles))

    strengths = (area or {}).get('strengths') or []
    if strengths:
        bullets = [
            Paragraph(f'<font color="{COLORS["good"]}">&#10003;</font> {esc(item)}', styles['Bullet'])
            for item in strengths
        ]
        flows.append(KeepTogether([Paragraph(esc(S['sub_working']), styles['SubHead']), bullets[0]]))
        flows.extend(bullets[1:])

    gaps = (area or {}).get('gaps') or []
    gaps_subhead = Paragraph(esc(S['sub_gaps']), styles['SubHead'])
    if gaps:
        # First finding flat-glued to the sub-heading; each finding atomic.
        flows.append(KeepTogether([gaps_subhead] + gap_flowables(gaps[0], styles, S)))
        for gap in gaps[1:]:
            flows.append(KeepTogether(gap_flowables(gap, styles, S)))
    else:
        flows.append(KeepTogether([gaps_subhead, Paragraph(esc(S['none']), styles['Body'])]))
    return flows


# ─── Enrichment tables (identity hygiene / break-glass / application risk) ───

def _er_cell_styles(styles):
    """Lightweight table-cell paragraph styles for the enrichment tables —
    a compact header style and a wrapping body/permissions style, matching
    this report's lighter layout."""
    base = styles['Body']
    return {
        'th': ParagraphStyle(
            'ErTh', parent=base, fontName='Helvetica-Bold', fontSize=8.5,
            textColor=white, leading=11, spaceAfter=0, alignment=TA_LEFT),
        'td': ParagraphStyle(
            'ErTd', parent=base, fontName='Helvetica', fontSize=8.5,
            textColor=HexColor(COLORS['text']), leading=11, spaceAfter=0,
            alignment=TA_LEFT),
    }


def _er_table(rows, col_widths, cell_styles):
    """Build a styled enrichment table from a header row + body rows. The
    first row is rendered as a primary-colored header band; body rows get a
    light hairline rule and zebra-free padding to stay airy."""
    table = Table(rows, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor(COLORS['primary'])),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor(COLORS['rule'])),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    return table


def _er_mfa(value, S):
    v = (value or '').lower()
    if v == 'yes':
        return S['er_yes']
    if v == 'no':
        return S['er_no']
    return S['er_unknown']


def _er_bool(value, S):
    return S['er_yes'] if value else S['er_no']


def _er_type(value, S):
    return S['er_guest'] if (value or '').lower() == 'guest' else S['er_member']


def _er_verdict(value, S):
    v = (value or '').lower()
    if v == 'green':
        return S['er_verdict_green']
    if v == 'yellow':
        return S['er_verdict_yellow']
    if v == 'red':
        return S['er_verdict_red']
    return S['er_verdict_none']


def _er_drift(value, S):
    return S['er_drift_yes'] if (value or '').lower() == 'drifted' else '—'


def _er_list(items, S):
    items = [str(i) for i in (items or []) if i]
    return ', '.join(items) if items else '—'


def _er_perms(items, S):
    # Cap the permissions shown in a table cell — ReportLab can't split a single
    # row across pages, so an app with a very large consent would make a row
    # taller than the page and crash the build. Full list is in the Apps tab + CSV.
    vals = [str(i) for i in (items or []) if i]
    if not vals:
        return '—'
    limit = 20
    if len(vals) > limit:
        return ', '.join(vals[:limit]) + ' ' + S['er_more'].replace('{n}', str(len(vals) - limit))
    return ', '.join(vals)


def _er_activity(entry, S):
    last = entry.get('lastActivity')
    if last:
        return str(last)
    if entry.get('neverRedeemed'):
        return S['er_never_redeemed']
    return '—'


def render_enrichment(enrichment, styles, S, width, lang='en'):
    """Render the identity-hygiene + break-glass + application-risk tables.
    Honors graceful-degradation per the enrichment contract: every block
    falls back to an explanatory line rather than an empty table, and never
    raises on missing keys."""
    cs = _er_cell_styles(styles)
    th, td = cs['th'], cs['td']
    flows = []

    identity = (enrichment.get('identity') or {})
    breakglass = (enrichment.get('breakGlass') or {})
    apps = (enrichment.get('apps') or {})

    # ── Admin accounts ──
    admin_content = []
    if not identity.get('available'):
        admin_content = [Paragraph(esc(S['er_identity_unavailable']), styles['Body'])]
    else:
        admins = identity.get('admins') or []
        if not admins:
            admin_content = [Paragraph(esc(S['er_no_admins']), styles['Body'])]
        else:
            header = [Paragraph(esc(S[k]), th) for k in (
                'er_col_account', 'er_col_roles', 'er_col_enabled',
                'er_col_mfa', 'er_col_activity')]
            rows = [header]
            for a in admins:
                account = a.get('account') or a.get('upn') or '—'
                if a.get('breakGlass'):
                    account = f"{account} ({S['er_breakglass_tag']})"
                rows.append([
                    Paragraph(esc(account), td),
                    Paragraph(esc(_er_list(a.get('roles'), S)), td),
                    Paragraph(esc(_er_bool(a.get('enabled'), S)), td),
                    Paragraph(esc(_er_mfa(a.get('mfa'), S)), td),
                    Paragraph(esc(_er_activity(a, S)), td),
                ])
            col_w = [width * f for f in (0.26, 0.32, 0.12, 0.12, 0.18)]
            admin_content = [_er_table(rows, col_w, cs)]
    flows.extend(section(S['er_sec_admins'], admin_content, styles, width))

    # ── Inactive accounts — split into members vs external/guests (Item 1) ──
    # NOTE: the shared gatherReportEnrichment() emits inactive_members +
    # inactive_guests (the old inactive_users key was removed in the posture-report
    # work); reading inactive_users here is what silently emptied this table.
    def _inactive_table(users_list, type_label):
        header = [Paragraph(esc(S[k]), th) for k in (
            'er_col_account', 'er_col_type', 'er_col_activity')]
        rows = [header]
        for u in users_list:
            account = u.get('account') or u.get('upn') or '—'
            rows.append([
                Paragraph(esc(account), td),
                Paragraph(esc(type_label), td),
                Paragraph(esc(_er_activity(u, S)), td),
            ])
        col_w = [width * f for f in (0.50, 0.18, 0.32)]
        return _er_table(rows, col_w, cs)

    if not identity.get('available'):
        flows.extend(section(S['er_sec_inactive_members'],
                             [Paragraph(esc(S['er_identity_unavailable']), styles['Body'])],
                             styles, width))
    else:
        threshold = identity.get('threshold_days')
        threshold_note = Paragraph(
            esc(S['er_threshold_note'].replace('{n}', str(threshold))), styles['GapMeta']
        ) if threshold is not None else None

        # New payload carries the split; fall back to a single list for older data.
        if identity.get('inactive_members') is not None or identity.get('inactive_guests') is not None:
            inactive_members = identity.get('inactive_members') or []
            inactive_guests = identity.get('inactive_guests') or []
        else:
            legacy = identity.get('inactive_users') or []
            inactive_members = [u for u in legacy if (u.get('type') or '').lower() != 'guest']
            inactive_guests = [u for u in legacy if (u.get('type') or '').lower() == 'guest']

        # Inactive members
        m_content = []
        if threshold_note is not None:
            m_content.append(threshold_note)
        if inactive_members:
            m_content.append(_inactive_table(inactive_members, S['er_member']))
        else:
            m_content.append(Paragraph(esc(S['er_no_inactive_members']), styles['Body']))
        flows.extend(section(S['er_sec_inactive_members'], m_content, styles, width))

        # Inactive external / guest accounts
        g_content = []
        guest_total = (identity.get('summary') or {}).get('guest_total')
        if guest_total is not None:
            g_content.append(Paragraph(esc(
                S['er_guest_count_note'].replace('{inactive}', str(len(inactive_guests))).replace('{total}', str(guest_total))
            ), styles['GapMeta']))
        if inactive_guests:
            g_content.append(_inactive_table(inactive_guests, S['er_guest_external']))
        else:
            g_content.append(Paragraph(esc(S['er_no_inactive_guests']), styles['Body']))
        flows.extend(section(S['er_sec_inactive_guests'], g_content, styles, width))

    # ── Break-glass (emergency access) ──
    bg_content = []
    if not breakglass.get('configured'):
        bg_content = [Paragraph(esc(S['er_bg_not_configured']), styles['Body'])]
    else:
        group_name = breakglass.get('group_name') or breakglass.get('group_id') or '—'
        bg_content.append(Paragraph(
            f"<b>{esc(S['er_bg_group_label'])}:</b> {esc(group_name)}", styles['Body']))
        if not breakglass.get('members_available'):
            bg_content.append(Paragraph(esc(S['er_bg_members_unavailable']), styles['Body']))
        else:
            members = breakglass.get('members') or []
            if not members:
                bg_content.append(Paragraph(
                    f"<b>{esc(S['er_bg_members_label'])}:</b> {esc(S['er_none'])}", styles['Body']))
            else:
                names = [m.get('account') or m.get('upn') or '—' for m in members]
                bg_content.append(Paragraph(
                    f"<b>{esc(S['er_bg_members_label'])}:</b> {esc(', '.join(names))}",
                    styles['Body']))
    flows.extend(section(S['er_sec_breakglass'], bg_content, styles, width))

    # ── Application risk ──
    app_content = []
    if not apps.get('available'):
        app_content = [Paragraph(esc(S['er_apps_unavailable']), styles['Body'])]
    else:
        others = apps.get('others') or []
        if not others:
            app_content = [Paragraph(esc(S['er_all_known_good']), styles['Body'])]
        else:
            header = [Paragraph(esc(S[k]), th) for k in (
                'er_col_app', 'er_col_publisher', 'er_col_verdict',
                'er_col_drift', 'er_col_permissions')]
            rows = [header]
            for app in others:
                rows.append([
                    Paragraph(esc(app.get('displayName') or '—'), td),
                    Paragraph(esc(app.get('publisher') or '—'), td),
                    Paragraph(esc(_er_verdict(app.get('verdict'), S)), td),
                    Paragraph(esc(_er_drift(app.get('drift_state'), S)), td),
                    Paragraph(esc(_er_perms(app.get('permissions'), S)), td),
                ])
            col_w = [width * f for f in (0.24, 0.20, 0.12, 0.10, 0.34)]
            app_content = [_er_table(rows, col_w, cs)]
    flows.extend(section(S['er_sec_app_risk'], app_content, styles, width))

    # ── Email authentication (primary domain detail; cached read, Item 2) ──
    email_auth = (enrichment.get('emailAuth') or {})
    primary = email_auth.get('primary') or {}
    ea_content = []
    if (not email_auth.get('available')) or (not primary):
        ea_content = [Paragraph(esc(S['email_auth_unavailable']), styles['Body'])]
    else:
        ea_content.append(Paragraph(esc(S['email_auth_intro']), styles['GapMeta']))

        # Gauge (shared grade-banded donut) + domain / caption / providers beside it.
        ea_buf = BytesIO()
        grade_word = email_auth_label(PROJECT_ROOT, lang, 'grade')
        if generate_email_auth_gauge(primary.get('overall_score'), primary.get('grade'), ea_buf, grade_word):
            ea_buf.seek(0)
            caption = email_auth_label(PROJECT_ROOT, lang,
                                       'non_mail_domain' if primary.get('non_mail') else 'gauge_caption')
            side = [Paragraph(f"<b>{esc(primary.get('domain') or '—')}</b>", styles['Body']),
                    Paragraph(esc(caption), td)]
            provs = ((primary.get('detected_providers') or {}).get('all')) or []
            if provs:
                side.append(Paragraph(esc(email_auth_label(
                    PROJECT_ROOT, lang, 'detected_providers', {'providers': ', '.join(provs)})), td))
            gauge_tbl = Table([[RLImage(ea_buf, width=1.6 * inch, height=1.6 * inch), side]],
                              colWidths=[1.8 * inch, width - 1.8 * inch])
            gauge_tbl.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ]))
            ea_content.append(gauge_tbl)

        # Per-mechanism status table (shared findings→rows mapping; DKIM 3-state).
        mech_rows_data = mechanism_rows(primary.get('findings') or {}, PROJECT_ROOT, lang)
        if mech_rows_data:
            header = [Paragraph(esc(S[k]), th) for k in (
                'ea_col_mechanism', 'ea_col_status', 'ea_col_detail')]
            rows = [header]
            for mech_name, status_lbl, detail in mech_rows_data:
                rows.append([Paragraph(esc(mech_name), td),
                             Paragraph(esc(status_lbl), td),
                             Paragraph(esc(detail), td)])
            col_w = [width * f for f in (0.18, 0.16, 0.66)]
            ea_content.append(_er_table(rows, col_w, cs))

        # Other mail domains — compact one-line-per-domain list (no gauge/table).
        others = email_auth.get('others') or []
        if others:
            lines = []
            for o in others:
                tag = ''
                if o.get('non_mail'):
                    tag = ' · ' + esc(email_auth_label(PROJECT_ROOT, lang, 'non_mail_domain'))
                lines.append(f"{esc(o.get('domain') or '—')} — {esc(str(o.get('grade') or ''))} "
                             f"({esc(str(o.get('overall_score', 0)))}){tag}")
            ea_content.append(Paragraph(esc(S['email_auth_other_domains']), styles['SubHead']))
            ea_content.append(Paragraph('<br/>'.join(lines), styles['Body']))

        # Non-mail advisory + informational (onmicrosoft) domains.
        nonmail = []
        if primary.get('non_mail') and primary.get('domain'):
            nonmail.append(primary.get('domain'))
        nonmail += [o.get('domain') for o in others if o.get('non_mail') and o.get('domain')]
        if nonmail:
            ea_content.append(Paragraph(
                esc(S['email_auth_nonmail_note'].replace('{domains}', ', '.join(nonmail))),
                styles['GapMeta']))
        info = email_auth.get('informational') or []
        if info:
            ea_content.append(Paragraph(esc(email_auth_label(
                PROJECT_ROOT, lang, 'informational_domains', {'domains': ', '.join(info)})),
                styles['GapMeta']))
    flows.extend(section(S['email_auth_title'], ea_content, styles, width))

    return flows


def count_findings_by_priority(analysis):
    counts = {'high': 0, 'medium': 0, 'low': 0}
    for key in ('conditional_access', 'intune', 'security_settings'):
        for gap in (analysis.get(key) or {}).get('gaps') or []:
            p = (gap.get('priority') or 'medium').lower()
            if p not in counts:
                p = 'medium'
            counts[p] += 1
    return counts


def make_cover(S, tenant_name, generated_iso, cover_path, prepared_by, logo_path):
    """First-page callback — full-bleed cover image + left-aligned title block.

    Matches the Security Posture report cover: optional MSP logo top-left in the
    whitest area, then a left-aligned stack (title, tenant, subtitle, generated,
    prepared-by)."""
    def _cover(canvas, doc):
        canvas.saveState()
        w, h = letter
        if cover_path:
            canvas.drawImage(cover_path, 0, 0, width=w, height=h,
                             preserveAspectRatio=True, anchor='c')

        left_x = 0.6 * inch
        logo_top = h * 0.70
        logo_max_w = 2.6 * inch
        logo_max_h = 1.15 * inch

        if logo_path:
            try:
                ir = ImageReader(logo_path)
                iw, ih = ir.getSize()
                scale = min(logo_max_w / iw, logo_max_h / ih)
                dw, dh = iw * scale, ih * scale
                canvas.drawImage(ir, left_x, logo_top - dh, width=dw, height=dh,
                                 mask='auto')
                cursor_y = logo_top - dh - 30
            except Exception:
                cursor_y = logo_top
        else:
            cursor_y = h * 0.64

        # Report title
        canvas.setFont('Helvetica-Bold', 26)
        canvas.setFillColor(HexColor('#1A2A3A'))
        canvas.drawString(left_x, cursor_y, S['title'])

        # Tenant (client) name
        cursor_y -= 26
        canvas.setFont('Helvetica', 16)
        canvas.setFillColor(HexColor('#2C3E50'))
        canvas.drawString(left_x, cursor_y, tenant_name or '—')

        # Subtitle
        cursor_y -= 22
        canvas.setFont('Helvetica', 12)
        canvas.setFillColor(HexColor('#4A5568'))
        canvas.drawString(left_x, cursor_y, S['subtitle'])

        # Generated timestamp
        cursor_y -= 18
        canvas.setFont('Helvetica', 10)
        canvas.setFillColor(HexColor('#666666'))
        canvas.drawString(left_x, cursor_y, f"{S['generated']}: {fmt_dt(generated_iso)}")

        # Prepared by (operator, falling back to MSP)
        cursor_y -= 22
        canvas.setFont('Helvetica-Oblique', 10)
        canvas.setFillColor(HexColor('#666666'))
        canvas.drawString(left_x, cursor_y, S['cover_prepared_by'].format(msp=prepared_by))
        canvas.restoreState()
    return _cover


def make_footer(S, msp_name, attribution_on):
    """Later-pages callback — thin rule + attribution + page number."""
    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(HexColor(COLORS['rule']))
        canvas.setLineWidth(0.5)
        canvas.line(0.75 * inch, 0.6 * inch, 7.75 * inch, 0.6 * inch)
        canvas.setFont('Helvetica', 7.5)
        canvas.setFillColor(HexColor(COLORS['text_light']))
        left = msp_name if msp_name else (S['attribution'] if attribution_on else '')
        if left:
            canvas.drawString(0.75 * inch, 0.42 * inch, left)
        canvas.drawRightString(7.75 * inch, 0.42 * inch, f"{S['page']} {doc.page}")
        canvas.restoreState()
    return _footer


def main():
    if len(sys.argv) < 3:
        sys.stderr.write('Usage: generate-quick-assessment-report.py <input.json> <output.pdf>\n')
        sys.exit(1)

    with open(sys.argv[1], 'r', encoding='utf-8') as fh:
        data = json.load(fh)
    output_path = sys.argv[2]

    lang = data.get('language', 'en')
    S = STRINGS.get(lang, STRINGS['en'])
    styles = build_styles()
    analysis = data.get('analysis') or {}
    tenant = data.get('tenant') or {}
    headline = data.get('headline') or {}
    report_config = data.get('reportConfig') or {}
    msp_name = report_config.get('mspName') or ''
    attribution_on = report_config.get('platformAttribution', True)
    # Cover "Prepared by" — logged-in operator's name, falling back to the MSP
    # name (or the platform name when neither is set).
    prepared_by = report_config.get('preparedBy') or msp_name or 'Panoptica365'
    # Optional MSP branding logo, drawn top-left on the cover when present.
    msp_logo_path = os.path.join(PROJECT_ROOT, 'data', 'branding', 'logo.png')
    if not os.path.exists(msp_logo_path):
        msp_logo_path = None
    width = letter[0] - 1.5 * inch  # matches the 0.75" left/right margins

    story = []

    # ─── Executive Summary (business-owner audience) — first content page ───
    # Plain-language page written for the client/owner, prepended before the
    # operator-grade technical report. Every field access is guarded: if the
    # model omitted "executive_summary" (older cache, malformed output), the
    # whole page is skipped and the technical report renders unchanged.
    exec_sum = analysis.get('executive_summary')
    if isinstance(exec_sum, dict):
        risks = exec_sum.get('business_risks')
        risks = [r for r in risks if r] if isinstance(risks, list) else []
        if exec_sum.get('verdict') or risks or exec_sum.get('recommended_path') or exec_sum.get('outlook'):
            exec_flows = []
            exec_flows.extend(prose(exec_sum.get('verdict'), styles))
            if risks:
                risk_bullets = [
                    Paragraph(f'<font color="{COLORS["accent"]}">&#8226;</font> {esc(r)}', styles['Bullet'])
                    for r in risks
                ]
                exec_flows.append(KeepTogether(
                    [Paragraph(esc(S['exec_risks_label']), styles['SubHead']), risk_bullets[0]]))
                exec_flows.extend(risk_bullets[1:])
            if exec_sum.get('recommended_path'):
                exec_flows.append(KeepTogether([
                    Paragraph(esc(S['exec_path_label']), styles['SubHead']),
                    Paragraph(esc(exec_sum.get('recommended_path')), styles['Body']),
                ]))
            if exec_sum.get('outlook'):
                exec_flows.append(KeepTogether([
                    Paragraph(esc(S['exec_outlook_label']), styles['SubHead']),
                    Paragraph(esc(exec_sum.get('outlook')), styles['Body']),
                ]))
            if exec_flows:
                story.extend(section(S['exec_summary_title'], exec_flows, styles, width))
                story.append(PageBreak())

    # ─── Page 2: meta line ───
    story.append(Paragraph(
        f"<b>{esc(S['tenant'])}:</b> {esc(tenant.get('display_name', '—'))}"
        f" &nbsp;|&nbsp; {esc(S['captured'])}: {esc(fmt_dt(data.get('capturedAt')))}",
        styles['Meta']))
    story.append(Spacer(1, 10))

    # ─── Headline cards ───
    cards = [
        (fmt_pct(headline.get('secure_score')), S['hl_secure']),
        (fmt_pct(headline.get('mfa_pct')), S['hl_mfa']),
        (str(headline.get('ca_policy_count')) if headline.get('ca_policy_count') is not None else '—', S['hl_ca']),
        (str(headline.get('security_settings_total')) if headline.get('security_settings_total') is not None else '—', S['hl_settings']),
    ]
    card_row = [
        Table([[Paragraph(esc(v), styles['CardValue'])], [Paragraph(esc(l), styles['CardLabel'])]],
              colWidths=[width / 4.0 - 6])
        for (v, l) in cards
    ]
    card_tbl = Table([card_row], colWidths=[width / 4.0] * 4)
    card_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor(COLORS['band'])),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(card_tbl)
    story.append(Spacer(1, 14))

    # ─── Charts: Secure Score gauge + Findings by priority ───
    chart_cells = []
    score_buf = BytesIO()
    if chart_score_gauge(headline.get('secure_score'), score_buf):
        score_buf.seek(0)
        chart_cells.append([
            RLImage(score_buf, width=1.9 * inch, height=1.9 * inch),
            S['chart_score'],
        ])
    findings_buf = BytesIO()
    if chart_findings_donut(count_findings_by_priority(analysis), findings_buf, S):
        findings_buf.seek(0)
        chart_cells.append([
            RLImage(findings_buf, width=1.9 * inch, height=1.9 * inch),
            S['chart_findings'],
        ])
    if chart_cells:
        col_w = width / len(chart_cells)
        cell_tables = [
            Table([[img], [Paragraph(esc(caption), styles['Caption'])]], colWidths=[col_w])
            for (img, caption) in chart_cells
        ]
        charts_tbl = Table([cell_tables], colWidths=[col_w] * len(chart_cells))
        charts_tbl.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(charts_tbl)
        story.append(Spacer(1, 12))

    # ─── Overall posture ───
    story.extend(section(S['sec_overall'],
                         prose(analysis.get('overall_posture'), styles) or
                         [Paragraph(esc(S['none']), styles['Body'])],
                         styles, width))

    # ─── CA / Intune / Security Settings ───
    for key, label in (
        ('conditional_access', S['sec_ca']),
        ('intune', S['sec_intune']),
        ('security_settings', S['sec_settings']),
    ):
        story.extend(section(label, render_area(analysis.get(key), styles, S), styles, width))

    # ─── New analysis narratives: Identity Posture + Application Risk ───
    story.extend(section(S['er_sec_identity'],
                         render_area(analysis.get('identity_posture'), styles, S),
                         styles, width))
    story.extend(section(S['er_sec_app_risk'],
                         render_area(analysis.get('application_risk'), styles, S),
                         styles, width))

    # ─── Enrichment tables (admins / inactive / break-glass / app risk) ───
    story.extend(render_enrichment(data.get('enrichment') or {}, styles, S, width, lang))

    # ─── Strengths summary ───
    if analysis.get('strengths_summary'):
        story.extend(section(S['sec_strengths'],
                             prose(analysis.get('strengths_summary'), styles),
                             styles, width))

    # ─── Priority actions ───
    action_flows = []
    actions = analysis.get('prioritized_actions') or []
    if actions:
        for idx, action in enumerate(actions, start=1):
            label, color = priority_label(action.get('priority'), S)
            head = (f'<b>{idx}.</b> <font color="{color}"><b>[{esc(label)}]</b></font> '
                    f'<b>{esc(action.get("title") or "")}</b>')
            if action.get('area'):
                head += f' <font color="{COLORS["text_light"]}">— {esc(action.get("area"))}</font>'
            block = [Paragraph(head, styles['Gap'])]
            if action.get('detail'):
                block.append(Paragraph(esc(action.get('detail')), styles['Gap']))
            tpl = action.get('deployable_template')
            if tpl:
                block.append(Paragraph(
                    f'&#10003; {esc(S["deployable"])} — {esc(S["tpl"])}: <b>{esc(tpl)}</b>',
                    styles['GapMeta']))
            else:
                block.append(Spacer(1, 6))
            action_flows.append(KeepTogether(block))
    else:
        action_flows.append(Paragraph(esc(S['none']), styles['Body']))
    story.extend(section(S['sec_actions'], action_flows, styles, width))

    # ─── Build: cover page first, body from page 2 ───
    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.7 * inch, bottomMargin=0.8 * inch,
        title=f"{S['title']} — {tenant.get('display_name', '')}",
    )
    cover = make_cover(S, tenant.get('display_name', ''), data.get('generatedAt'),
                       find_cover_image(), prepared_by, msp_logo_path)
    footer = make_footer(S, msp_name, attribution_on)
    doc.build([Spacer(1, 1), PageBreak()] + story,
              onFirstPage=cover, onLaterPages=footer)
    print(f'Quick Assessment PDF written: {output_path}')


if __name__ == '__main__':
    main()
