#!/usr/bin/env python3
"""
Panoptica365 — Quick Assessment Report Generator (v0.1.6)

Renders the Opus deep gap analysis into a narrative advisory PDF: a branded
cover page, headline metrics + charts, then Conditional Access / Intune /
Security Settings sections (each with narrative + strengths + gaps), a
strengths summary, and a prioritized action list.

Input JSON (argv[1]) is assembled by src/routes/api-reports.js — see the
quick-assessment route. Output PDF path is argv[2].

Usage: python3 generate-quick-assessment-report.py <input.json> <output.pdf>
"""

import sys
import os
import json
import html
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether,
    PageBreak, Image as RLImage,
)

import matplotlib
matplotlib.use('Agg')  # headless — no display
import matplotlib.pyplot as plt

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ─── Palette (consistent with the other Panoptica reports) ───
COLORS = {
    'primary':    '#2C3E50',
    'accent':     '#C9A961',
    'text':       '#333333',
    'text_light': '#666666',
    'rule':       '#D9D9D9',
    'band':       '#F4F2EC',
    'high':       '#C0392B',
    'medium':     '#D68910',
    'low':        '#7F8C8D',
    'good':       '#1E8449',
}

# ─── Localized static chrome (the AI narrative is already localized) ───
STRINGS = {
    'en': {
        'title': 'Quick Assessment',
        'subtitle': 'Microsoft 365 Security — Point-in-Time Assessment',
        'tenant': 'Tenant',
        'generated': 'Generated',
        'captured': 'Configuration captured',
        'hl_secure': 'Secure Score',
        'hl_mfa': 'MFA Registration',
        'hl_ca': 'CA Policies',
        'hl_settings': 'Security Settings',
        'sec_overall': 'Overall Posture',
        'sec_ca': 'Conditional Access',
        'sec_intune': 'Intune & Device Management',
        'sec_settings': 'Security Settings Posture',
        'sec_strengths': 'Strengths',
        'sec_actions': 'Priority Actions',
        'sub_working': 'What is working',
        'sub_gaps': 'Gaps & recommendations',
        'deployable': 'One-click template available',
        'tpl': 'Template',
        'none': 'No items noted.',
        'prio_high': 'High',
        'prio_medium': 'Medium',
        'prio_low': 'Low',
        'chart_score': 'Microsoft Secure Score',
        'chart_findings': 'Findings by Priority',
        'findings_unit': 'findings',
        'attribution': 'Generated by Panoptica365',
        'page': 'Page',
    },
    'fr': {
        'title': 'Évaluation rapide',
        'subtitle': 'Sécurité Microsoft 365 — Évaluation ponctuelle',
        'tenant': 'Locataire',
        'generated': 'Généré le',
        'captured': 'Configuration relevée le',
        'hl_secure': 'Score de sécurité',
        'hl_mfa': 'Inscription MFA',
        'hl_ca': 'Politiques AC',
        'hl_settings': 'Paramètres de sécurité',
        'sec_overall': 'Posture globale',
        'sec_ca': 'Accès conditionnel',
        'sec_intune': 'Intune et gestion des appareils',
        'sec_settings': 'Posture des paramètres de sécurité',
        'sec_strengths': 'Points forts',
        'sec_actions': 'Actions prioritaires',
        'sub_working': 'Ce qui fonctionne',
        'sub_gaps': 'Lacunes et recommandations',
        'deployable': 'Modèle déployable en un clic',
        'tpl': 'Modèle',
        'none': 'Aucun élément relevé.',
        'prio_high': 'Élevée',
        'prio_medium': 'Moyenne',
        'prio_low': 'Faible',
        'chart_score': 'Score de sécurité Microsoft',
        'chart_findings': 'Constats par priorité',
        'findings_unit': 'constats',
        'attribution': 'Généré par Panoptica365',
        'page': 'Page',
    },
    'es': {
        'title': 'Evaluación rápida',
        'subtitle': 'Seguridad de Microsoft 365 — Evaluación puntual',
        'tenant': 'Inquilino',
        'generated': 'Generado el',
        'captured': 'Configuración capturada el',
        'hl_secure': 'Puntuación de seguridad',
        'hl_mfa': 'Registro de MFA',
        'hl_ca': 'Políticas de AC',
        'hl_settings': 'Configuración de seguridad',
        'sec_overall': 'Postura general',
        'sec_ca': 'Acceso condicional',
        'sec_intune': 'Intune y gestión de dispositivos',
        'sec_settings': 'Postura de configuración de seguridad',
        'sec_strengths': 'Fortalezas',
        'sec_actions': 'Acciones prioritarias',
        'sub_working': 'Lo que funciona',
        'sub_gaps': 'Brechas y recomendaciones',
        'deployable': 'Plantilla disponible en un clic',
        'tpl': 'Plantilla',
        'none': 'Sin elementos.',
        'prio_high': 'Alta',
        'prio_medium': 'Media',
        'prio_low': 'Baja',
        'chart_score': 'Puntuación de seguridad de Microsoft',
        'chart_findings': 'Hallazgos por prioridad',
        'findings_unit': 'hallazgos',
        'attribution': 'Generado por Panoptica365',
        'page': 'Página',
    },
}


def esc(value):
    """Escape text for ReportLab paragraph markup; lift **bold** to <b>."""
    if value is None:
        return ''
    text = html.escape(str(value), quote=False)
    while '**' in text:
        text = text.replace('**', '<b>', 1)
        if '**' in text:
            text = text.replace('**', '</b>', 1)
        else:
            text += '</b>'
    return text


def fmt_pct(value):
    if value is None:
        return '—'
    try:
        return f'{round(float(value))}%'
    except (TypeError, ValueError):
        return str(value)


def fmt_dt(iso):
    if not iso:
        return '—'
    try:
        return datetime.fromisoformat(str(iso).replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M UTC')
    except ValueError:
        return str(iso)


def find_cover_image():
    """Canonical Panoptica365 cover; fall back to the repo-root asset."""
    for candidate in (
        os.path.join(PROJECT_ROOT, 'public', 'img', 'report-cover.png'),
        os.path.join(PROJECT_ROOT, 'Panoptica365 Report Cover.png'),
    ):
        if os.path.exists(candidate):
            return candidate
    return None


def build_styles():
    base = getSampleStyleSheet()
    styles = {}
    styles['Subtitle'] = ParagraphStyle(
        'QaSubtitle', parent=base['Normal'], fontName='Helvetica',
        fontSize=11, textColor=HexColor(COLORS['text_light']), leading=15)
    styles['Meta'] = ParagraphStyle(
        'QaMeta', parent=base['Normal'], fontName='Helvetica',
        fontSize=9.5, textColor=HexColor(COLORS['text_light']), leading=14)
    styles['Section'] = ParagraphStyle(
        'QaSection', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=14, textColor=white, leading=18)
    styles['SubHead'] = ParagraphStyle(
        'QaSubHead', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=10.5, textColor=HexColor(COLORS['primary']), leading=14,
        spaceBefore=8, spaceAfter=3)
    styles['Body'] = ParagraphStyle(
        'QaBody', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=15,
        spaceAfter=6, alignment=TA_LEFT)
    styles['Bullet'] = ParagraphStyle(
        'QaBullet', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=14,
        leftIndent=14, bulletIndent=4, spaceAfter=3)
    styles['Gap'] = ParagraphStyle(
        'QaGap', parent=base['Normal'], fontName='Helvetica',
        fontSize=10, textColor=HexColor(COLORS['text']), leading=14,
        spaceAfter=2)
    styles['GapMeta'] = ParagraphStyle(
        'QaGapMeta', parent=base['Normal'], fontName='Helvetica-Oblique',
        fontSize=8.5, textColor=HexColor(COLORS['text_light']), leading=12,
        spaceAfter=8)
    styles['CardValue'] = ParagraphStyle(
        'QaCardValue', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=18, textColor=HexColor(COLORS['primary']), leading=20,
        alignment=TA_CENTER)
    styles['CardLabel'] = ParagraphStyle(
        'QaCardLabel', parent=base['Normal'], fontName='Helvetica',
        fontSize=8, textColor=HexColor(COLORS['text_light']), leading=10,
        alignment=TA_CENTER)
    styles['Caption'] = ParagraphStyle(
        'QaCaption', parent=base['Normal'], fontName='Helvetica-Bold',
        fontSize=8.5, textColor=HexColor(COLORS['text_light']), leading=11,
        alignment=TA_CENTER)
    return styles


# ─── Charts (matplotlib, headless) ───

def chart_score_gauge(score_pct, buf):
    """Donut gauge for the Microsoft Secure Score. Returns False if no data."""
    if score_pct is None:
        return False
    try:
        score = float(score_pct)
    except (TypeError, ValueError):
        return False

    fig, ax = plt.subplots(figsize=(2.6, 2.6))
    ring = COLORS['good'] if score >= 70 else COLORS['medium'] if score >= 45 else COLORS['high']
    ax.pie([score, max(0.0, 100 - score)], colors=[ring, '#E8E8E8'],
           startangle=90, counterclock=False,
           wedgeprops=dict(width=0.32, edgecolor='white', linewidth=2))
    ax.text(0, 0, f'{round(score)}%', ha='center', va='center',
            fontsize=26, fontweight='bold', color=COLORS['primary'])
    ax.set(aspect='equal')
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    return True


def chart_findings_donut(counts, buf, S):
    """Donut of findings by priority (high/medium/low). False if no findings."""
    order = [('high', S['prio_high'], COLORS['high']),
             ('medium', S['prio_medium'], COLORS['medium']),
             ('low', S['prio_low'], COLORS['low'])]
    values, colors_list = [], []
    for key, _label, color in order:
        cnt = counts.get(key, 0)
        if cnt > 0:
            values.append(cnt)
            colors_list.append(color)
    total = sum(values)
    if total == 0:
        return False

    fig, ax = plt.subplots(figsize=(2.6, 2.6))
    ax.pie(values, colors=colors_list, startangle=90, counterclock=False,
           wedgeprops=dict(width=0.32, edgecolor='white', linewidth=2))
    ax.text(0, 0.07, str(total), ha='center', va='center',
            fontsize=24, fontweight='bold', color=COLORS['primary'])
    ax.text(0, -0.20, S['findings_unit'], ha='center', va='center',
            fontsize=8, color=COLORS['text_light'])
    ax.set(aspect='equal')
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    return True


def prose(text, styles):
    """Split a narrative string on blank lines into separate paragraphs."""
    flows = []
    if not text:
        return flows
    for chunk in [c.strip() for c in str(text).replace('\r', '').split('\n\n') if c.strip()]:
        flows.append(Paragraph(esc(chunk).replace('\n', '<br/>'), styles['Body']))
    return flows


def section_header(label, styles, width):
    """A full-width colored section bar."""
    tbl = Table([[Paragraph(esc(label), styles['Section'])]], colWidths=[width])
    tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor(COLORS['primary'])),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    return tbl


def section(label, content_flows, styles, width):
    """A section: the header bar is glued to its first content flowable via
    KeepTogether, so a header can never be orphaned at the foot of a page."""
    header = section_header(label, styles, width)
    if not content_flows:
        return [header, Spacer(1, 12)]
    head_group = KeepTogether([header, Spacer(1, 8), content_flows[0]])
    return [head_group] + content_flows[1:] + [Spacer(1, 12)]


def priority_label(priority, S):
    p = (priority or '').lower()
    if p == 'high':
        return S['prio_high'], COLORS['high']
    if p == 'low':
        return S['prio_low'], COLORS['low']
    return S['prio_medium'], COLORS['medium']


def gap_flowables(gap, styles, S):
    """The raw flowables for one finding — title + priority tag, detail, and
    the optional template line. Returned as a flat list so callers can wrap
    them in a single (non-nested) KeepTogether."""
    label, color = priority_label(gap.get('priority'), S)
    head = (f'<font color="{color}"><b>[{esc(label)}]</b></font> '
            f'<b>{esc(gap.get("title") or "")}</b>')
    out = [Paragraph(head, styles['Gap'])]
    if gap.get('detail'):
        out.append(Paragraph(esc(gap.get('detail')), styles['Gap']))
    tpl = gap.get('deployable_template')
    if tpl:
        out.append(Paragraph(
            f'&#10003; {esc(S["deployable"])} — {esc(S["tpl"])}: <b>{esc(tpl)}</b>',
            styles['GapMeta']))
    else:
        out.append(Spacer(1, 4))
    return out


def render_area(area, styles, S):
    """Render a CA / Intune / Security-Settings section's content flowables.
    Each finding is one atomic KeepTogether and the "Gaps" sub-heading is
    flat-glued to the first finding — no nested KeepTogethers, which would
    mis-measure and strand whitespace at page ends."""
    flows = []
    flows.extend(prose((area or {}).get('narrative'), styles))

    strengths = (area or {}).get('strengths') or []
    if strengths:
        bullets = [
            Paragraph(f'<font color="{COLORS["good"]}">&#10003;</font> {esc(item)}', styles['Bullet'])
            for item in strengths
        ]
        flows.append(KeepTogether([Paragraph(esc(S['sub_working']), styles['SubHead']), bullets[0]]))
        flows.extend(bullets[1:])

    gaps = (area or {}).get('gaps') or []
    gaps_subhead = Paragraph(esc(S['sub_gaps']), styles['SubHead'])
    if gaps:
        # First finding flat-glued to the sub-heading; each finding atomic.
        flows.append(KeepTogether([gaps_subhead] + gap_flowables(gaps[0], styles, S)))
        for gap in gaps[1:]:
            flows.append(KeepTogether(gap_flowables(gap, styles, S)))
    else:
        flows.append(KeepTogether([gaps_subhead, Paragraph(esc(S['none']), styles['Body'])]))
    return flows


def count_findings_by_priority(analysis):
    counts = {'high': 0, 'medium': 0, 'low': 0}
    for key in ('conditional_access', 'intune', 'security_settings'):
        for gap in (analysis.get(key) or {}).get('gaps') or []:
            p = (gap.get('priority') or 'medium').lower()
            if p not in counts:
                p = 'medium'
            counts[p] += 1
    return counts


def make_cover(S, tenant_name, generated_iso, cover_path):
    """First-page callback — full-bleed cover image + title text."""
    def _cover(canvas, doc):
        canvas.saveState()
        w, h = letter
        if cover_path:
            canvas.drawImage(cover_path, 0, 0, width=w, height=h,
                             preserveAspectRatio=True, anchor='c')
        canvas.setFont('Helvetica-Bold', 30)
        canvas.setFillColor(HexColor('#1A2A3A'))
        canvas.drawCentredString(w / 2, h * 0.79, S['title'])
        canvas.setFont('Helvetica', 13)
        canvas.setFillColor(HexColor('#4A5568'))
        canvas.drawCentredString(w / 2, h * 0.745, S['subtitle'])
        canvas.setFont('Helvetica-Bold', 17)
        canvas.setFillColor(HexColor(COLORS['primary']))
        canvas.drawCentredString(w / 2, h * 0.69, tenant_name or '—')
        canvas.setFont('Helvetica', 10)
        canvas.setFillColor(HexColor('#666666'))
        canvas.drawCentredString(w / 2, h * 0.655,
                                 f"{S['generated']}: {fmt_dt(generated_iso)}")
        canvas.restoreState()
    return _cover


def make_footer(S, msp_name, attribution_on):
    """Later-pages callback — thin rule + attribution + page number."""
    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(HexColor(COLORS['rule']))
        canvas.setLineWidth(0.5)
        canvas.line(0.75 * inch, 0.6 * inch, 7.75 * inch, 0.6 * inch)
        canvas.setFont('Helvetica', 7.5)
        canvas.setFillColor(HexColor(COLORS['text_light']))
        left = msp_name if msp_name else (S['attribution'] if attribution_on else '')
        if left:
            canvas.drawString(0.75 * inch, 0.42 * inch, left)
        canvas.drawRightString(7.75 * inch, 0.42 * inch, f"{S['page']} {doc.page}")
        canvas.restoreState()
    return _footer


def main():
    if len(sys.argv) < 3:
        sys.stderr.write('Usage: generate-quick-assessment-report.py <input.json> <output.pdf>\n')
        sys.exit(1)

    with open(sys.argv[1], 'r', encoding='utf-8') as fh:
        data = json.load(fh)
    output_path = sys.argv[2]

    lang = data.get('language', 'en')
    S = STRINGS.get(lang, STRINGS['en'])
    styles = build_styles()
    analysis = data.get('analysis') or {}
    tenant = data.get('tenant') or {}
    headline = data.get('headline') or {}
    report_config = data.get('reportConfig') or {}
    msp_name = report_config.get('mspName') or ''
    attribution_on = report_config.get('platformAttribution', True)
    width = letter[0] - 1.5 * inch  # matches the 0.75" left/right margins

    story = []

    # ─── Page 2: meta line ───
    story.append(Paragraph(
        f"<b>{esc(S['tenant'])}:</b> {esc(tenant.get('display_name', '—'))}"
        f" &nbsp;|&nbsp; {esc(S['captured'])}: {esc(fmt_dt(data.get('capturedAt')))}",
        styles['Meta']))
    story.append(Spacer(1, 10))

    # ─── Headline cards ───
    cards = [
        (fmt_pct(headline.get('secure_score')), S['hl_secure']),
        (fmt_pct(headline.get('mfa_pct')), S['hl_mfa']),
        (str(headline.get('ca_policy_count')) if headline.get('ca_policy_count') is not None else '—', S['hl_ca']),
        (str(headline.get('security_settings_total')) if headline.get('security_settings_total') is not None else '—', S['hl_settings']),
    ]
    card_row = [
        Table([[Paragraph(esc(v), styles['CardValue'])], [Paragraph(esc(l), styles['CardLabel'])]],
              colWidths=[width / 4.0 - 6])
        for (v, l) in cards
    ]
    card_tbl = Table([card_row], colWidths=[width / 4.0] * 4)
    card_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor(COLORS['band'])),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(card_tbl)
    story.append(Spacer(1, 14))

    # ─── Charts: Secure Score gauge + Findings by priority ───
    chart_cells = []
    score_buf = BytesIO()
    if chart_score_gauge(headline.get('secure_score'), score_buf):
        score_buf.seek(0)
        chart_cells.append([
            RLImage(score_buf, width=1.9 * inch, height=1.9 * inch),
            S['chart_score'],
        ])
    findings_buf = BytesIO()
    if chart_findings_donut(count_findings_by_priority(analysis), findings_buf, S):
        findings_buf.seek(0)
        chart_cells.append([
            RLImage(findings_buf, width=1.9 * inch, height=1.9 * inch),
            S['chart_findings'],
        ])
    if chart_cells:
        col_w = width / len(chart_cells)
        cell_tables = [
            Table([[img], [Paragraph(esc(caption), styles['Caption'])]], colWidths=[col_w])
            for (img, caption) in chart_cells
        ]
        charts_tbl = Table([cell_tables], colWidths=[col_w] * len(chart_cells))
        charts_tbl.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(charts_tbl)
        story.append(Spacer(1, 12))

    # ─── Overall posture ───
    story.extend(section(S['sec_overall'],
                         prose(analysis.get('overall_posture'), styles) or
                         [Paragraph(esc(S['none']), styles['Body'])],
                         styles, width))

    # ─── CA / Intune / Security Settings ───
    for key, label in (
        ('conditional_access', S['sec_ca']),
        ('intune', S['sec_intune']),
        ('security_settings', S['sec_settings']),
    ):
        story.extend(section(label, render_area(analysis.get(key), styles, S), styles, width))

    # ─── Strengths summary ───
    if analysis.get('strengths_summary'):
        story.extend(section(S['sec_strengths'],
                             prose(analysis.get('strengths_summary'), styles),
                             styles, width))

    # ─── Priority actions ───
    action_flows = []
    actions = analysis.get('prioritized_actions') or []
    if actions:
        for idx, action in enumerate(actions, start=1):
            label, color = priority_label(action.get('priority'), S)
            head = (f'<b>{idx}.</b> <font color="{color}"><b>[{esc(label)}]</b></font> '
                    f'<b>{esc(action.get("title") or "")}</b>')
            if action.get('area'):
                head += f' <font color="{COLORS["text_light"]}">— {esc(action.get("area"))}</font>'
            block = [Paragraph(head, styles['Gap'])]
            if action.get('detail'):
                block.append(Paragraph(esc(action.get('detail')), styles['Gap']))
            tpl = action.get('deployable_template')
            if tpl:
                block.append(Paragraph(
                    f'&#10003; {esc(S["deployable"])} — {esc(S["tpl"])}: <b>{esc(tpl)}</b>',
                    styles['GapMeta']))
            else:
                block.append(Spacer(1, 6))
            action_flows.append(KeepTogether(block))
    else:
        action_flows.append(Paragraph(esc(S['none']), styles['Body']))
    story.extend(section(S['sec_actions'], action_flows, styles, width))

    # ─── Build: cover page first, body from page 2 ───
    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.7 * inch, bottomMargin=0.8 * inch,
        title=f"{S['title']} — {tenant.get('display_name', '')}",
    )
    cover = make_cover(S, tenant.get('display_name', ''), data.get('generatedAt'), find_cover_image())
    footer = make_footer(S, msp_name, attribution_on)
    doc.build([Spacer(1, 1), PageBreak()] + story,
              onFirstPage=cover, onLaterPages=footer)
    print(f'Quick Assessment PDF written: {output_path}')


if __name__ == '__main__':
    main()
